In [21]:
import numpy as np

In [27]:
X = np.array(([0,0,0], [0,1,0],[1,0,0],[1,1,0],[0,0,1],[0,1,1],[1,0,1],[1,1,1]), dtype = float)
Y = np.array(([0],[1],[1],[0],[1],[0],[0],[1]), dtype =float)
X_test = np.array(([0.3,0.3,0.3], [1,1,0.3],[0.3,0.3,1]), dtype = float)

In [28]:
class NeuralNetwork(object):
    def __init__(self):
        self.inputSize = 3
        self.outputSize = 1
        self.hiddenSize = 3
    
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize)
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize)
    
    def feedForward(self, X):
        self.z = np.dot(X, self.W1)
        self.z2 = self.sigmoid(self.z)
        self.z3 = np.dot(self.z2, self.W2)
        output = self.sigmoid(self.z3)
        return output
    
    def sigmoid(self, s, deriv = False):
        if deriv == True:
            return s*(1-s)
        return 1/(1 + np.exp(-s))
    
    def backward(self, X,y, output):
        self.output_error = y-output
        self.output_delta = self.output_error*self.sigmoid(output, deriv = True)
        
        self.z2_error = self.output_delta.dot(self.W2.T)
        self.z2_delta = self.z2_error*self.sigmoid(self.z2, deriv = True)
        
        self.W1 += X.T.dot(self.z2_delta)
        self.W2 += self.z2.T.dot(self.output_delta)
        
    def train(self, X, Y):
        output = self.feedForward(X)
        self.backward(X, Y, output)
        
    def test(self, X_test):
        output_test = self.feedForward(X_test)
        #self.backward(X, Y, output)
        
NN = NeuralNetwork()

for i in range(5000):
    #if (i % 100 == 0):
       # print("loss: "+ str(np.mean(np.square(Y-NN.feedForward(X)))))
    NN.train(X,Y)

print("input: "+ str(X))
print("actual output: "+ str(Y))
print("loss: "+ str(np.mean(np.square(Y-NN.feedForward(X)))))
print("\n")
print("Predicted Output: "+ str(NN.feedForward(X)))

input: [[0. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
actual output: [[0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]]
loss: 0.0010671325979997627


Predicted Output: [[0.04538796]
 [0.9653758 ]
 [0.94801481]
 [0.02621499]
 [0.96539335]
 [0.00140404]
 [0.02624615]
 [0.99985628]]


In [29]:
for i in range(5000):
    NN.test(X_test)
print("Predicted Output: "+ str(NN.feedForward(X_test)))

Predicted Output: [[0.71173644]
 [0.33292958]
 [0.95467095]]
